// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simulate_sir
List simulate_sir(SEXP Rparams, double dt, int max_num_dt, int min_epi_size, int maximum_attempts, bool track_transmissions);
RcppExport SEXP EpiGenR_simulate_sir(SEXP RparamsSEXP, SEXP dtSEXP, SEXP max_num_dtSEXP, SEXP min_epi_sizeSEXP, SEXP maximum_attemptsSEXP, SEXP track_transmissionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type Rparams(RparamsSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type max_num_dt(max_num_dtSEXP);
    Rcpp::traits::input_parameter< int >::type min_epi_size(min_epi_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type maximum_attempts(maximum_attemptsSEXP);
    Rcpp::traits::input_parameter< bool >::type track_transmissions(track_transmissionsSEXP);
    __result = Rcpp::wrap(simulate_sir(Rparams, dt, max_num_dt, min_epi_size, maximum_attempts, track_transmissions));
    return __result;
END_RCPP
}
// get_transmission_tree
NumericMatrix get_transmission_tree(SEXP Repidemic);
RcppExport SEXP EpiGenR_get_transmission_tree(SEXP RepidemicSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type Repidemic(RepidemicSEXP);
    __result = Rcpp::wrap(get_transmission_tree(Repidemic));
    return __result;
END_RCPP
}
